### PR TITLE
Add support for the trafficlight4

### PR DESCRIPTION
**Pull request by mupuf**
Cleware stopped selling its older versions of the traffic light in favor of their newer version. The new version enables independent control of the LEDs in all directions (12 choices instead of 3), and is controlled using the "Switch" interface.

This Pull Request adds support for the new product ID, then adds support for directionality.

### CODE REVIEW

**Review by timofurrer — APPROVED** [review]
🎉

**Comment by mupuf** [comment]
Glad you like it :p

**Comment by mupuf** [comment]
@joshrost: Gentle ping :)

**Comment by joshuarost** [comment]
Very nice! Thanks for the feature! I'm sorry I didn't see it earlier ✌️

**Comment by mupuf** [comment]
You are welcome :) And thanks a lot, Josh!

I'll be waiting for a new release in pypi next :p

**Comment by joshuarost** [comment]
I have some exams coming up and won't be able to do the release at least until July @mupuf

**Comment by mupuf** [comment]
No hurry! Good luck for your exams!

**Comment by joshuarost** [comment]
@mupuf  I just tried to set up a pipeline with Github actions to automatically deploy new versions to Pypi, but realized that the automatic tests don't work anymore. Either I will fix that the next time I have some spare time, or you try to fix them.

**Comment by mupuf** [comment]
Sorry about this, Josh!

I can try fixing them, as it is my fault for breaking them to begin with!

**Pull request merged**
